version: '3.9'
services:
  origin:
    build: org
    container_name: demo_origin
    ports:
      - 80:80
    volumes:
      - ./org/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./org/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./org/log:/var/log/nginx
      - ./org/html:/usr/share/nginx/html:ro

  cdn:
    build: cdn
    container_name: demo_cdn
    ports:
      - 443:443
    volumes:
      - ./cdn/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cdn/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./cdn/log:/var/log/nginx
      - ./cdn/certs:/etc/nginx/certs:ro
    # define additional alias "origin.box" (see https://docs.docker.com/compose/networking/#links)
    links:
      - 'origin:origin.box'
